name: Android CI
on: [push, pull_request]

env:
  JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set JAVA_HOME and Gradle Java Home
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
      - run: ./gradlew lint testDebugUnitTest assembleDebug
      - run: ./gradlew jacocoTestReport
      - run: bash scripts/security-audit.sh
      - run: ./gradlew connectedCheck -Pandroid.testInstrumentationRunnerArguments.class=com.example.n8nmonitor.ui.*
      - run: ./gradlew bundleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            app/build/reports/jacoco/
            build/reports/test-execution-report.md